### ISSUE TITLE
Running Jest test failing 

### ISSUE THREAD

**Issue by NourIM** [prezly/slate#407]
Hi there, after I installed @prezly/slate-lists into my project and ran the jest test, I started getting the following error 
<img width="1259" alt="Screenshot 2023-05-09 at 13 43 40" src="https://github.com/prezly/slate/assets/14943545/c4a16ee8-2534-40cd-a21e-26de9e67bb53">

**Comment by NourIM** [comment]
Hi @e1himself, thanks for replying!
Unfortunately, it's a private repo, and I we are not using Babel. I'm trying this solution for now  https://stackoverflow.com/a/73388333/9999257

**Comment by e1himself** [comment]
@NourIM from what I understood, currently the test framework rely a lot on intercepting module resolution in `node` by registering their own hooks to transpile code on the fly. This is, for example, how Typescript tests work. However, there is no way of intercepting ESM modules importing in Node at the moment. That's why the test frameworks struggle with it. 

So the safest bet would be to make sure that the required packages get transformed to CommonJS on the fly (changing Jest's `transformIgnorePatterns` is related to this).

As of this repo, I've struggled with Jest a lot and in the end, I've switched the code to Mocha (74347ae611324a2cd202893c41b104dcd5f54d39)  -- it's less an out-of-the-box solution and requires more configuration, but at least, the configuration allowed us to fine-tune it to work in our environment.
