### ISSUE TITLE
cra .mjs support

### ISSUE THREAD

**Issue by remusgls** [prezly/slate#67]
Hello,

I'm trying to implement the @prezly/slate-list plugin for a existing react project, created with **create-react-app** (w typescript), but there seems to be a issue, when trying to put it all togheter:

```
./node_modules/@prezly/slate-commons/build/esm/EditableWithExtensions.mjs
Can't import the named export 'Editable' from non EcmaScript module (only default export is available)
```

Is there a workaround for this, without having to through different packages to support .mjs, like react app rewired?

Thank you!

**Comment by e1himself** [comment]
@remusgls there were a number of patches made since Jan 3, addressing various ESM/CommonJS interoperability issues. 

Can you please try again with the newest release? If the issue persists, it would also be great if you post reproduction steps so we can track down the problem.

Thank you for reporting this :+1:

**Comment by e1himself** [comment]
@remusgls I'm going to close this issue for lack of activity. Feel free to comment here if you still encounter the problem.
